#dsn="root:root@tcp(127.0.0.1:33060)/larabbs_upgrade?charset=utf8mb4&parseTime=True&loc=Local"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 33060
  database: larabbs_upgrade
  charset: utf8mb4
